-- Seed master diagnosis POSKESTREN (idempotent; jalankan kapan saja)
INSERT INTO poskestren_diagnosis (id, name, is_active) VALUES
  ('seed-abses', 'ABSES', 1),
  ('seed-asthenia', 'ASTHENIA', 1),
  ('seed-asthma', 'ASTHMA', 1),
  ('seed-cepalgia', 'CEPALGIA', 1),
  ('seed-common-cold', 'COMMON COLD', 1),
  ('seed-dermatitis', 'DERMATITIS', 1),
  ('seed-diare', 'DIARE', 1),
  ('seed-dispepsia', 'DISPEPSIA', 1),
  ('seed-faringitis', 'FARINGITIS', 1),
  ('seed-gastritis', 'GASTRITIS', 1),
  ('seed-gingivitis', 'GINGIVITIS', 1),
  ('seed-hepatitis', 'HEPATITIS', 1),
  ('seed-herdeolum', 'HORDEOLUM', 1),
  ('seed-herpes', 'HERPES', 1),
  ('seed-impetigo', 'IMPETIGO', 1),
  ('seed-ispa', 'ISPA', 1),
  ('seed-konjungtivitis', 'KONJUNGTIVITIS', 1),
  ('seed-myalgia', 'MYALGIA', 1),
  ('seed-odontalgia', 'ODONTALGIA', 1),
  ('seed-otitis', 'OTITIS', 1),
  ('seed-paronichia', 'PARONICHIA', 1),
  ('seed-peny-kulit-lain', 'PENY. KULIT LAIN', 1),
  ('seed-pioderma', 'PIODERMA', 1),
  ('seed-scabies', 'SCABIES', 1),
  ('seed-stomatitis', 'STOMATITIS', 1),
  ('seed-thypoid', 'TYPHOID', 1),
  ('seed-urtikaria', 'URTIKARIA', 1),
  ('seed-lain-lain', 'LAIN-LAIN', 1)
ON CONFLICT(name) DO NOTHING;
