'use client'
/* eslint-disable @next/next/no-img-element */

import { useCallback,useEffect,useMemo,useRef,useState,useTransition } from 'react'
import { ArrowClockwise,CheckCircle,DownloadSimple,IdentificationCard,Play,Printer,Scan,Warning } from '@phosphor-icons/react'
import { toast } from 'sonner'
import { createQrBatchAction,getCredentialBatchAction,getCredentialFilters,getLatestCredentialBatchAction,getRfidEnrollmentQueueAction,issueCredentialAction,processQrBatchAction,searchCredentialStudents,setCredentialModeAction,type CredentialStudentRow } from './actions'
import type { CredentialMode } from '@/lib/finance/types'
import { useKeyboardWedgeScanner } from '@/lib/finance/scanner-client'

type Filters={q:string;asrama:string;kamar:string;kelas:string;status:string}
type Batch={id:string;status:string;total_count:number;processed_count:number;success_count:number;failed_count:number;errors?:Array<{santri_id:string;error_message:string|null}>}|null
type CardPreview={id:string;cardNumber:string;nis:string;name:string;asrama:string|null;kamar:string|null;photoUrl:string|null;kelas:string|null;qrSvg:string}
const emptyFilters:Filters={q:'',asrama:'',kamar:'',kelas:'',status:'ALL'}

const badge=(value:string|null)=>value?<span className={`rounded-full px-2 py-1 text-[10px] font-bold ${value==='ACTIVE'?'bg-emerald-50 text-emerald-700':'bg-amber-50 text-amber-800'}`}>{value}</span>:<span className="rounded-full bg-slate-100 px-2 py-1 text-[10px] text-slate-500">BELUM ADA</span>

export function CredentialClient({initialMode}:{initialMode:CredentialMode}){
  const [pending,startTransition]=useTransition(),[mode,setMode]=useState<CredentialMode>(initialMode),[from,setFrom]=useState<'RFID'|'QR'>('RFID'),[ends,setEnds]=useState('')
  const [filters,setFilters]=useState<Filters>(emptyFilters),[options,setOptions]=useState<{asramas:string[];kamars:string[];kelas:string[]}>({asramas:[],kamars:[],kelas:[]})
  const [rows,setRows]=useState<CredentialStudentRow[]>([]),[allSelectable,setAllSelectable]=useState<Array<{id:string;qr_id:string|null;rfid_id:string|null}>>([]),[page,setPage]=useState(1),[totalPages,setTotalPages]=useState(1),[total,setTotal]=useState(0)
  const [selected,setSelected]=useState<Set<string>>(new Set()),[loading,setLoading]=useState(true),[batch,setBatch]=useState<Batch>(null)
  const [rfidQueue,setRfidQueue]=useState<CredentialStudentRow[]>([]),[rfidIndex,setRfidIndex]=useState(0),[rfidValue,setRfidValue]=useState(''),[readerTest,setReaderTest]=useState('')
  const [exporting,setExporting]=useState<number|null>(null),[preview,setPreview]=useState<CardPreview|null>(null),rfidInput=useRef<HTMLInputElement>(null)

  const load=useCallback(async(nextPage=page,nextFilters=filters)=>{setLoading(true);try{const result=await searchCredentialStudents({...nextFilters,page:nextPage,pageSize:50});setRows(result.rows);setAllSelectable(result.allSelectable);setTotal(result.total);setTotalPages(result.totalPages);setPage(result.page)}finally{setLoading(false)}},[filters,page])
  useEffect(()=>{getCredentialFilters().then(setOptions);getLatestCredentialBatchAction().then(value=>setBatch(value as Batch));void load(1)},[]) // eslint-disable-line react-hooks/exhaustive-deps
  useEffect(()=>{if(rfidQueue.length)rfidInput.current?.focus()},[rfidIndex,rfidQueue.length])

  const currentRfid=rfidQueue[rfidIndex]||null
  const enrollRfid=useCallback(async(raw:string)=>{
    if(!currentRfid)return
    const value=raw.trim();if(value.length<4){toast.error('UID RFID terlalu pendek.');return}
    const result=await issueCredentialAction({santriId:currentRfid.id,kind:'RFID_UID',rawToken:value})
    if('error'in result){toast.error(result.error);return}
    toast.success(`RFID ${currentRfid.nama_lengkap} tersimpan.`);setRfidValue('');setRfidIndex(index=>index+1);void load(page)
  },[currentRfid,load,page])
  useKeyboardWedgeScanner(value=>{if(currentRfid)void enrollRfid(value);else setReaderTest(value)},true)

  const selectedRows=useMemo(()=>allSelectable.filter(row=>selected.has(row.id)),[allSelectable,selected])
  const qrIds=selectedRows.map(row=>row.qr_id).filter((id):id is string=>Boolean(id))
  const volumes=Array.from({length:Math.ceil(qrIds.length/400)},(_,index)=>qrIds.slice(index*400,index*400+400))
  const pageSelected=rows.length>0&&rows.every(row=>selected.has(row.id)),allFilteredSelected=allSelectable.length>0&&allSelectable.every(row=>selected.has(row.id))

  const togglePage=()=>setSelected(current=>{const next=new Set(current);if(pageSelected)rows.forEach(row=>next.delete(row.id));else rows.forEach(row=>next.add(row.id));return next})
  const selectAllFiltered=()=>setSelected(allFilteredSelected?new Set():new Set(allSelectable.map(row=>row.id)))
  const applyMode=()=>startTransition(async()=>{const result=mode==='BOTH_TRANSITION'?await setCredentialModeAction({mode,transitionFrom:from,transitionTo:from==='RFID'?'QR':'RFID',transitionEndsAt:new Date(ends).toISOString()}):await setCredentialModeAction({mode});if('error'in result)toast.error(result.error);else toast.success('Mode credential diperbarui.')})

  const runBatch=async(batchId:string)=>{
    let active=await getCredentialBatchAction(batchId) as Batch;setBatch(active)
    while(active&&['PENDING','PROCESSING','COMPLETED_WITH_ERRORS'].includes(active.status)){
      const result=await processQrBatchAction(batchId)
      if('error'in result){toast.error(result.error);break}
      active=result.batch as Batch;setBatch(active)
      if(active&&['COMPLETED','COMPLETED_WITH_ERRORS'].includes(active.status))break
    }
    await load(page);toast.success(active?.failed_count?`Batch selesai dengan ${active.failed_count} kegagalan.`:'Penerbitan QR selesai.')
  }
  const createQrBatch=()=>startTransition(async()=>{const ids=[...selected];if(!ids.length){toast.error('Pilih santri terlebih dahulu.');return}const result=await createQrBatchAction({santriIds:ids,filter:filters});if('error'in result){toast.error(result.error);return}await runBatch(result.id)})

  const startRfidQueue=()=>startTransition(async()=>{const ids=allSelectable.filter(row=>selected.has(row.id)&&!row.rfid_id).map(row=>row.id);if(!ids.length){toast.error('Semua santri terpilih sudah memiliki RFID.');return}const queue=await getRfidEnrollmentQueueAction(ids);if(!queue.length){toast.error('Tidak ada santri yang dapat dimasukkan ke antrean RFID.');await load(page);return}setRfidQueue(queue);setRfidIndex(0);setRfidValue('')})
  const downloadVolume=async(ids:string[],index:number)=>{setExporting(index);try{const response=await fetch('/api/finance/credentials/cards',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({credentialIds:ids})});if(!response.ok){const payload=await response.json().catch(()=>({}));throw new Error(payload.error||'Gagal membuat PDF kartu.')}const blob=await response.blob(),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=`kartu-qr-santri-volume-${index+1}.pdf`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast.success(`PDF volume ${index+1} diunduh.`)}catch(error){toast.error(error instanceof Error?error.message:'Gagal membuat PDF.')}finally{setExporting(null)}}
  const loadPreview=async()=>{if(!qrIds[0])return;const response=await fetch(`/api/finance/credentials/cards?id=${encodeURIComponent(qrIds[0])}`,{cache:'no-store'}),payload=await response.json() as CardPreview&{error?:string};if(!response.ok){toast.error(payload.error||'Preview tidak tersedia.');return}setPreview(payload)}

  return <div className="space-y-5">
    <section className="grid gap-4 xl:grid-cols-[1fr_1.25fr]">
      <div className="rounded-xl border bg-white p-4"><h2 className="font-bold">Mode credential global</h2><p className="mt-1 text-xs text-slate-500">HYBRID menerima RFID dan QR secara permanen.</p><div className="mt-3 grid gap-2 sm:grid-cols-[1fr_auto]"><select value={mode} onChange={event=>setMode(event.target.value as CredentialMode)} className="min-h-11 rounded-xl border px-3 py-2"><option value="HYBRID">RFID + QR aktif</option><option value="RFID">RFID saja</option><option value="QR">QR saja</option><option value="BOTH_TRANSITION">Mode transisi</option></select><button disabled={pending||(mode==='BOTH_TRANSITION'&&!ends)} onClick={applyMode} className="min-h-11 rounded-xl bg-emerald-700 px-4 py-2 font-bold text-white disabled:opacity-50">Terapkan</button></div>{mode==='BOTH_TRANSITION'?<div className="mt-2 grid gap-2 sm:grid-cols-2"><select value={from} onChange={event=>setFrom(event.target.value as 'RFID'|'QR')} className="min-h-11 rounded-xl border px-3"><option value="RFID">RFID ke QR</option><option value="QR">QR ke RFID</option></select><input type="datetime-local" value={ends} onChange={event=>setEnds(event.target.value)} className="min-h-11 rounded-xl border px-3"/></div>:null}</div>
      <div className="rounded-xl border bg-white p-4"><div className="flex items-center gap-2"><Scan className="h-5 w-5 text-emerald-700"/><h2 className="font-bold">Uji USB reader / scanner</h2></div><p className="mt-1 text-xs text-slate-500">Klik area kosong, lalu tempel kartu atau scan QR. Reader harus mengirim Enter.</p><div className="mt-3 rounded-xl border border-dashed p-4 font-mono text-sm">{readerTest?<span className="text-emerald-700">Terbaca: {readerTest}</span>:<span className="text-slate-400">Siap menerima scan...</span>}</div></div>
    </section>

    <section className="rounded-xl border bg-white"><div className="border-b p-4"><div className="flex flex-col gap-3 xl:flex-row xl:items-end xl:justify-between"><div><h2 className="font-bold">Pilih santri</h2><p className="text-xs text-slate-500">Filter hasil, pilih sebagian atau semua, lalu jalankan enrollment.</p></div><div className="flex flex-wrap gap-2"><button onClick={createQrBatch} disabled={pending||!selected.size} className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-emerald-700 px-4 py-2 text-sm font-bold text-white disabled:opacity-50"><Play className="h-4 w-4"/>Terbitkan QR ({selected.size})</button><button onClick={startRfidQueue} disabled={pending||!selected.size} className="inline-flex min-h-11 items-center gap-2 rounded-xl border px-4 py-2 text-sm font-bold disabled:opacity-50"><IdentificationCard className="h-4 w-4"/>Antrean RFID</button></div></div>
        <div className="mt-4 grid gap-2 sm:grid-cols-2 xl:grid-cols-6"><input value={filters.q} onChange={event=>setFilters({...filters,q:event.target.value})} placeholder="Nama atau NIS" className="min-h-11 rounded-xl border px-3 xl:col-span-2"/><select value={filters.asrama} onChange={event=>setFilters({...filters,asrama:event.target.value})} className="min-h-11 rounded-xl border px-3"><option value="">Semua asrama</option>{options.asramas.map(value=><option key={value}>{value}</option>)}</select><select value={filters.kamar} onChange={event=>setFilters({...filters,kamar:event.target.value})} className="min-h-11 rounded-xl border px-3"><option value="">Semua kamar</option>{options.kamars.map(value=><option key={value}>{value}</option>)}</select><select value={filters.kelas} onChange={event=>setFilters({...filters,kelas:event.target.value})} className="min-h-11 rounded-xl border px-3"><option value="">Semua kelas</option>{options.kelas.map(value=><option key={value}>{value}</option>)}</select><select value={filters.status} onChange={event=>setFilters({...filters,status:event.target.value})} className="min-h-11 rounded-xl border px-3"><option value="ALL">Semua status</option><option value="MISSING_QR">Belum punya QR</option><option value="MISSING_RFID">Belum punya RFID</option><option value="HAS_QR">Sudah punya QR</option><option value="HAS_RFID">Sudah punya RFID</option></select></div><div className="mt-2 flex gap-2"><button onClick={()=>void load(1)} className="min-h-10 rounded-lg border px-3 text-sm font-bold">Terapkan filter</button><button onClick={()=>{setFilters(emptyFilters);setSelected(new Set());void load(1,emptyFilters)}} className="min-h-10 px-3 text-sm text-slate-500">Reset</button></div>
      </div>
      <div className="flex flex-wrap items-center justify-between gap-2 border-b bg-slate-50 px-4 py-2 text-xs"><div className="flex items-center gap-3"><label className="flex items-center gap-2"><input type="checkbox" checked={pageSelected} onChange={togglePage}/> Pilih halaman</label><button onClick={selectAllFiltered} className="font-bold text-emerald-700">{allFilteredSelected?'Batalkan semua':`Pilih semua ${total} hasil`}</button></div><span>{selected.size} dipilih</span></div>
      <div className="divide-y">{loading?<p className="p-10 text-center text-sm text-slate-500">Memuat santri...</p>:rows.length?rows.map(row=><label key={row.id} className="grid cursor-pointer gap-3 p-3 hover:bg-slate-50 sm:grid-cols-[auto_1fr_auto_auto] sm:items-center"><input type="checkbox" checked={selected.has(row.id)} onChange={()=>setSelected(current=>{const next=new Set(current);if(next.has(row.id))next.delete(row.id);else next.add(row.id);return next})}/><div className="flex min-w-0 items-center gap-3">{row.foto_url?<img src={row.foto_url} alt="" className="h-11 w-9 rounded object-cover"/>:<div className="grid h-11 w-9 place-items-center rounded bg-slate-100 text-xs font-bold">{row.nama_lengkap.slice(0,1)}</div>}<div><p className="font-semibold">{row.nama_lengkap}</p><p className="text-xs text-slate-500">{row.nis} · {row.kelas_pesantren||'-'} · {row.asrama||'-'} / {row.kamar||'-'}</p></div></div><div className="flex items-center gap-2 text-xs"><span>RFID</span>{badge(row.rfid_status)}</div><div className="flex items-center gap-2 text-xs"><span>QR</span>{badge(row.qr_status)}</div></label>):<p className="p-10 text-center text-sm text-slate-500">Tidak ada santri sesuai filter.</p>}</div>
      <div className="flex items-center justify-between p-3 text-sm"><button disabled={page<=1} onClick={()=>void load(page-1)} className="rounded-lg border px-3 py-2 disabled:opacity-40">Sebelumnya</button><span>Halaman {page} / {totalPages}</span><button disabled={page>=totalPages} onClick={()=>void load(page+1)} className="rounded-lg border px-3 py-2 disabled:opacity-40">Berikutnya</button></div>
    </section>

    {currentRfid?<section className="rounded-xl border-2 border-emerald-300 bg-emerald-50 p-4"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase text-emerald-700">Enrollment RFID {rfidIndex+1}/{rfidQueue.length}</p><h2 className="mt-1 text-xl font-black">{currentRfid.nama_lengkap}</h2><p className="text-sm">{currentRfid.nis} · {currentRfid.kelas_pesantren||'-'} · {currentRfid.asrama||'-'}</p></div><button onClick={()=>setRfidQueue([])} className="text-sm text-slate-500">Tutup</button></div><input ref={rfidInput} data-scanner-input value={rfidValue} onChange={event=>setRfidValue(event.target.value)} onKeyDown={event=>{if(event.key==='Enter'){event.preventDefault();void enrollRfid(rfidValue)}}} placeholder="Tempel kartu RFID - UID akan masuk di sini" className="mt-4 min-h-14 w-full rounded-xl border-2 border-emerald-400 bg-white px-4 font-mono text-lg outline-none"/><div className="mt-2 flex justify-between text-xs"><span>Scan berhasil akan otomatis lanjut.</span><button onClick={()=>setRfidIndex(index=>index+1)} className="font-bold text-amber-700">Lewati santri</button></div></section>:rfidQueue.length?<section className="rounded-xl bg-emerald-50 p-5 text-center"><CheckCircle className="mx-auto h-8 w-8 text-emerald-700"/><p className="mt-2 font-bold">Antrean RFID selesai.</p><button onClick={()=>setRfidQueue([])} className="mt-2 text-sm text-emerald-700">Tutup</button></section>:null}

    {batch?<section className="rounded-xl border bg-white p-4"><div className="flex items-center justify-between"><div><h2 className="font-bold">Batch QR terakhir</h2><p className="text-xs text-slate-500">{batch.id}</p></div><span className="rounded-full bg-blue-50 px-3 py-1 text-xs font-bold text-blue-700">{batch.status}</span></div><div className="mt-3 h-3 overflow-hidden rounded-full bg-slate-100"><div className="h-full bg-emerald-600" style={{width:`${batch.total_count?batch.processed_count/batch.total_count*100:0}%`}}/></div><div className="mt-2 flex flex-wrap gap-3 text-xs"><span>{batch.processed_count}/{batch.total_count} diproses</span><span className="text-emerald-700">{batch.success_count} baru</span><span>{batch.processed_count-batch.success_count-batch.failed_count} dilewati</span><span className="text-red-700">{batch.failed_count} gagal</span></div>{['PROCESSING','PENDING','COMPLETED_WITH_ERRORS'].includes(batch.status)?<button disabled={pending} onClick={()=>startTransition(()=>runBatch(batch.id))} className="mt-3 inline-flex min-h-11 items-center gap-2 rounded-xl border px-4 text-sm font-bold"><ArrowClockwise className="h-4 w-4"/>Lanjutkan / retry</button>:null}{batch.errors?.length?<div className="mt-3 rounded-xl bg-red-50 p-3 text-xs text-red-800">{batch.errors.map(error=><p key={error.santri_id}>{error.santri_id}: {error.error_message}</p>)}</div>:null}</section>:null}

    <section className="rounded-xl border bg-white p-4"><div className="flex items-center gap-2"><Printer className="h-5 w-5 text-emerald-700"/><div><h2 className="font-bold">Export kartu QR CR80 dua sisi</h2><p className="text-xs text-slate-500">Delapan kartu per A4. Halaman belakang sudah dicerminkan untuk duplex long-edge.</p></div></div>{!qrIds.length?<p className="mt-4 rounded-xl bg-amber-50 p-3 text-sm text-amber-900"><Warning className="mr-1 inline h-4 w-4"/>Pilih santri yang sudah memiliki QR aktif.</p>:<div className="mt-4 grid gap-2 sm:grid-cols-2 xl:grid-cols-3"><button onClick={()=>void loadPreview()} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl border px-4 py-3 text-sm font-bold"><IdentificationCard className="h-4 w-4"/>Preview kartu pertama</button>{volumes.map((ids,index)=><button key={index} disabled={exporting!==null} onClick={()=>void downloadVolume(ids,index)} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl border px-4 py-3 text-sm font-bold disabled:opacity-50"><DownloadSimple className="h-4 w-4"/>{exporting===index?'Membuat PDF...':`Unduh volume ${index+1} (${ids.length} kartu)`}</button>)}</div>}</section>
    {preview?<div className="fixed inset-0 z-[70] grid place-items-center overflow-y-auto bg-slate-950/75 p-4" onClick={()=>setPreview(null)}><div className="w-full max-w-4xl rounded-2xl bg-white p-4" onClick={event=>event.stopPropagation()}><div className="mb-4 flex items-center justify-between"><div><h2 className="font-bold">Preview kartu CR80 dua sisi</h2><p className="text-xs text-slate-500">Tampilan diperkecil; PDF memakai ukuran fisik 85,60 × 53,98 mm.</p></div><button onClick={()=>setPreview(null)} className="rounded-lg bg-slate-100 px-3 py-2 text-sm">Tutup</button></div><div className="grid gap-4 md:grid-cols-2"><div className="aspect-[1.586] overflow-hidden rounded-xl border bg-gradient-to-br from-white via-white to-emerald-50 p-5 shadow"><div className="flex items-center gap-3 border-b border-emerald-600 pb-3"><img src="/logo.png" alt="" className="h-10 w-10 object-contain"/><div><b className="text-xs text-emerald-800">PONDOK PESANTREN SUKAHIDENG</b><p className="text-[10px] text-slate-500">Kartu Identitas Santri</p></div></div><div className="mt-4 flex gap-4">{preview.photoUrl?<img src={preview.photoUrl} alt="" className="h-28 w-24 rounded-lg object-cover"/>:<div className="grid h-28 w-24 place-items-center rounded-lg bg-slate-200 text-xl font-black">{String(preview.name).slice(0,1)}</div>}<div><h3 className="font-black uppercase">{preview.name}</h3><p className="text-xs font-bold text-emerald-700">NIS {preview.nis}</p><p className="mt-3 text-xs">Kelas: <b>{preview.kelas||'-'}</b><br/>Asrama: <b>{preview.asrama||'-'}</b><br/>Kamar: <b>{preview.kamar||'-'}</b></p></div></div></div><div className="flex aspect-[1.586] items-center gap-5 rounded-xl bg-gradient-to-br from-emerald-900 to-emerald-700 p-6 text-white shadow"><div className="h-32 w-32 shrink-0 rounded-lg bg-white p-2 [&_svg]:h-full [&_svg]:w-full" dangerouslySetInnerHTML={{__html:preview.qrSvg}}/><div><b>SCAN DI LOKET KEUANGAN</b><p className="mt-2 font-mono text-xs text-emerald-100">{preview.cardNumber}</p><p className="mt-3 text-xs">Kartu bukan penyimpan saldo. Setiap transaksi tetap memerlukan PIN.</p></div></div></div></div></div>:null}
  </div>
}
