'use client'
import { useRouter } from 'next/navigation'
import { useRef,useState,useTransition } from 'react'
import { issueCredentialAction,markCredentialAction } from './actions'
export function CredentialActions({id,santriId,status}:{id:string;santriId:string;status:string}){
 const dialog=useRef<HTMLDialogElement>(null),[next,setNext]=useState('BLOCKED'),[pending,start]=useTransition(),[error,setError]=useState(''),router=useRouter()
 const terminal=['LOST','REVOKED'].includes(status)
 return <><div className="flex flex-wrap gap-2">{[{value:'REISSUE',label:'Kartu pengganti'},...terminal?[]:[{value:status==='BLOCKED'?'ACTIVE':'BLOCKED',label:status==='BLOCKED'?'Buka blokir':'Blokir'},{value:'LOST',label:'Hilang'},{value:'REVOKED',label:'Cabut'}]].map(a=><button key={a.value} className="min-h-11 rounded-lg border px-3 text-sm" onClick={()=>{setNext(a.value);setError('');dialog.current?.showModal()}}>{a.label}</button>)}</div><dialog ref={dialog} className="m-auto w-full max-w-md rounded-2xl p-5 backdrop:bg-black/40"><form onSubmit={e=>{e.preventDefault();const reason=String(new FormData(e.currentTarget).get('reason')||'');start(async()=>{try{const r=next==='REISSUE'?await issueCredentialAction({santriId,kind:'QR_STATIC',reissue:true}):await markCredentialAction(id,next as 'ACTIVE'|'BLOCKED'|'LOST'|'REVOKED',reason);if('error' in r){setError(r.error||'Gagal');return}dialog.current?.close();router.refresh()}catch(e){setError(e instanceof Error?e.message:'Gagal')}})}}><h3 className="font-bold">Perubahan kartu QR</h3><p className="my-3 text-sm">Kartu hilang, dicabut, atau diganti tidak dapat digunakan lagi.</p><label className="block text-sm">Alasan<textarea name="reason" required minLength={5} className="mt-2 min-h-24 w-full rounded-xl border p-3"/></label>{error&&<p role="alert" className="text-red-700">{error}</p>}<div className="mt-4 flex justify-end gap-2"><button type="button" onClick={()=>dialog.current?.close()} className="min-h-11 rounded-lg border px-4">Batal</button><button disabled={pending} className="min-h-11 rounded-lg bg-emerald-700 px-4 text-white">Simpan</button></div></form></dialog></>
}
