'use client'
/* eslint-disable @typescript-eslint/no-explicit-any */
import { useState,useTransition } from 'react'
import { toast } from 'sonner'
import { checkPayoutAction,createPayoutAction,executeApiPayoutAction,executePayoutAction,reconcilePayoutAction,registerRecipientAction,verifyRecipientAction } from './actions'

export function PayoutClient({payouts,recipients}:{payouts:any[];recipients:any[]}){
  const[pending,start]=useTransition(),[showRecipient,setShowRecipient]=useState(false)
  const act=(fn:()=>Promise<any>,message='Status payout diperbarui.')=>start(async()=>{const r=await fn();if('error'in r)toast.error(r.error);else toast.success(message)})
  return <div className="space-y-5">
    <div className="grid gap-5 lg:grid-cols-2">
      <form className="rounded-2xl border bg-white p-5" action={form=>act(()=>createPayoutAction({recipientId:String(form.get('recipient')),payoutType:String(form.get('type')) as any,amountRupiah:Number(form.get('amount')),method:String(form.get('method')) as any,requestKey:crypto.randomUUID()}),'Payout diajukan ke checker.')}><h2 className="font-bold">Ajukan payout</h2><div className="mt-3 grid gap-3"><select name="recipient" required className="rounded-xl border px-3 py-2"><option value="">Pilih penerima</option>{recipients.filter(r=>r.status==='ACTIVE').map(r=><option key={r.id} value={r.id}>{r.name} · {r.account_number_masked}</option>)}</select><select name="type" className="rounded-xl border px-3 py-2"><option value="MEAL">Uang makan</option><option value="LAUNDRY">Laundry</option><option value="PAYROLL">Payroll</option><option value="REFUND">Refund</option><option value="OTHER">Lainnya</option></select><input name="amount" type="number" min={1} required placeholder="Nominal" className="rounded-xl border px-3 py-2"/><select name="method" className="rounded-xl border px-3 py-2"><option value="API">Duitku API (BI-Fast)</option><option value="MANUAL_TRANSFER">Transfer manual</option><option value="CASH">Cash</option></select><button disabled={pending} className="rounded-xl bg-emerald-700 px-4 py-2 text-white">Ajukan</button></div></form>
      <section className="rounded-2xl border bg-white p-5"><div className="flex items-center justify-between"><h2 className="font-bold">Rekening penerima</h2><button onClick={()=>setShowRecipient(!showRecipient)} className="rounded-lg border px-3 py-1 text-sm">Tambah</button></div>{showRecipient&&<form className="mt-3 grid gap-2" action={form=>act(()=>registerRecipientAction({recipientType:String(form.get('recipientType')) as any,name:String(form.get('name')),bankCode:String(form.get('bankCode')),accountNumber:String(form.get('accountNumber')),accountHolderName:String(form.get('accountHolder'))}),'Rekening didaftarkan dan dibekukan 24 jam.')}><select name="recipientType" className="rounded-lg border px-3 py-2"><option value="MEAL_MANAGER">Pengelola makan</option><option value="LAUNDRY_MANAGER">Pengelola laundry</option><option value="TEACHER">Guru</option><option value="OTHER">Lainnya</option></select><input name="name" required placeholder="Nama penerima" className="rounded-lg border px-3 py-2"/><input name="bankCode" required placeholder="Kode bank 3 digit" className="rounded-lg border px-3 py-2"/><input name="accountNumber" required placeholder="Nomor rekening" className="rounded-lg border px-3 py-2"/><input name="accountHolder" required placeholder="Nama pemilik rekening" className="rounded-lg border px-3 py-2"/><button className="rounded-lg border border-emerald-700 px-3 py-2 text-emerald-800">Daftarkan</button></form>}<div className="mt-3 space-y-2">{recipients.map(r=><div key={r.id} className="flex justify-between rounded-lg bg-slate-50 p-2 text-sm"><span>{r.name} · {r.account_number_masked}<small className="block text-slate-500">{r.status}</small></span>{r.status==='PENDING_VERIFICATION'&&<button disabled={pending} onClick={()=>act(()=>verifyRecipientAction(r.id),'Rekening diverifikasi; cooling period tetap berlaku.')} className="rounded border px-2">Verifikasi</button>}</div>)}</div></section>
    </div>
    <div className="overflow-hidden rounded-2xl border bg-white">{payouts.length?payouts.map(p=><div key={p.id} className="grid gap-2 border-b p-4 last:border-0 md:grid-cols-[1fr_auto]"><div><p className="font-semibold">{p.recipient_name} · Rp {Number(p.amount_rupiah).toLocaleString('id-ID')}</p><p className="text-xs text-slate-500">{p.payout_type} · {p.method} · {p.status}</p></div><div className="flex flex-wrap gap-2">{p.status==='SUBMITTED'&&<button disabled={pending} onClick={()=>act(()=>checkPayoutAction(p.id))} className="rounded-lg border px-3 py-1 text-sm">Periksa</button>}{p.status==='CHECKED'&&p.method==='API'&&<button disabled={pending} onClick={()=>act(()=>executeApiPayoutAction(p.id))} className="rounded-lg bg-emerald-700 px-3 py-1 text-sm text-white">Kirim via API</button>}{p.status==='CHECKED'&&p.method!=='API'&&<button disabled={pending} onClick={()=>{const ref=prompt('Referensi transfer/kuitansi');if(ref)act(()=>executePayoutAction({id:p.id,reference:ref}))}} className="rounded-lg bg-emerald-700 px-3 py-1 text-sm text-white">Eksekusi</button>}{p.status==='PROVIDER_SUCCESS'&&<button disabled={pending} onClick={()=>act(()=>reconcilePayoutAction(p.id))} className="rounded-lg border px-3 py-1 text-sm">Rekonsiliasi</button>}</div></div>):<p className="p-4 text-sm text-slate-500">Belum ada payout.</p>}</div>
  </div>
}
